### ISSUE TITLE
README.md file needs improvements

### ISSUE THREAD

**Issue by dabiged** [dabiged/Volve2OPM#2]
Explanation on how to run install flow
running flow

serial vs threaded.
Screenshot of comparison in resinsight.

**Comment by dabiged** [comment]
Added screenshot.
Added installation and running instructions.

**Comment by discover-volve** [comment]
You installation steps say that you run a Volve_2020 model. Seems like you modified the actual model. Can you please share your changes. 
I try to run the Volve_2016.data file with the OPM simulator and get an error
`Error: String: '2950.0      128.8' invalid. Too many records in keyword: RSVD at: 236.
`
Please help me run the model.
